language: r
dist: bionic
cache: packages

r_packages:
  - knitr
  - testthat

r_github_packages:
  - richelbilderbeek/mhcnuggetsr

before_script:
  - sudo apt install python3-pip
  - Rscript -e "mhcnuggetsr::mhcnuggetsr_report()"
  - Rscript -e "mhcnuggetsr::install_mhcnuggets()"
  - Rscript -e "mhcnuggetsr::mhcnuggetsr_report()"

after_script:
  - travis_wait 120 Rscript scripts/run.R

after_failure:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_success:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

