language: r
dist: bionic
cache: packages

r_packages:
  - knitr
  - testthat

r_github_packages:
  - richelbilderbeek/mhcnuggetsr

before_script:
  - sudo apt install python3-pip
  - Rscript -e "mhcnuggetsr::mhcnuggetsr_report()"
  - Rscript -e "mhcnuggetsr::install_mhcnuggets()"
  - Rscript -e "mhcnuggetsr::mhcnuggetsr_report()"

after_script:
  - travis_wait 120 Rscript scripts/run.R

