language: r
dist: bionic
cache: packages

r_packages:
  - knitr
  - testthat

r_github_packages:
  - richelbilderbeek/mhcnuggetsr@develop

before_script:
  - sudo apt install python3-pip
  - sudo pip install --upgrade pip
  - Rscript -e "mhcnuggetsr::install_mhcnuggets()"

after_script:
  - travis_wait 120 Rscript scripts/run.R

